project:
  type: website

website:
  title: "Built Environment, Pedestrian Injuries, and Deep Learning"
  navbar:
    background: warning
    right:
      - text: 'Home'
        href: index.qmd
      - text: 'About'
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css

execute: 
  cache: true
  freeze: true
editor: visual

