project:
  type: website

website:
  title: "Built Environment, Pedestrian Injuries, and Deep Learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

